### ISSUE TITLE
Project Checklist

### ISSUE THREAD

**Issue by ablionit** [ablionit/testgit#1]
- [ ] Understand Project Requirements
- [ ] solCRM Entry & Update
- [ ] Assign Team
- [ ] Get Design Specifications
- [ ] Start Design
